/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SidebarLayoutImport } from './routes/_sidebarLayout'
import { Route as SidebarLayoutIndexImport } from './routes/_sidebarLayout/index'
import { Route as SidebarLayoutSearchImport } from './routes/_sidebarLayout/search'
import { Route as SidebarLayoutLibraryImport } from './routes/_sidebarLayout/library'

// Create/Update Routes

const SidebarLayoutRoute = SidebarLayoutImport.update({
  id: '/_sidebarLayout',
  getParentRoute: () => rootRoute,
} as any)

const SidebarLayoutIndexRoute = SidebarLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => SidebarLayoutRoute,
} as any)

const SidebarLayoutSearchRoute = SidebarLayoutSearchImport.update({
  path: '/search',
  getParentRoute: () => SidebarLayoutRoute,
} as any)

const SidebarLayoutLibraryRoute = SidebarLayoutLibraryImport.update({
  path: '/library',
  getParentRoute: () => SidebarLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebarLayout': {
      preLoaderRoute: typeof SidebarLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_sidebarLayout/library': {
      preLoaderRoute: typeof SidebarLayoutLibraryImport
      parentRoute: typeof SidebarLayoutImport
    }
    '/_sidebarLayout/search': {
      preLoaderRoute: typeof SidebarLayoutSearchImport
      parentRoute: typeof SidebarLayoutImport
    }
    '/_sidebarLayout/': {
      preLoaderRoute: typeof SidebarLayoutIndexImport
      parentRoute: typeof SidebarLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  SidebarLayoutRoute.addChildren([
    SidebarLayoutLibraryRoute,
    SidebarLayoutSearchRoute,
    SidebarLayoutIndexRoute,
  ]),
])

/* prettier-ignore-end */
